name: Build Container

on:
  push:
    tags:
    - "v*"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

      - name: checkout
        uses: actions/checkout@v2

      - name: login to cr.lab.cip.uw.edu
        uses: docker/login-action@v1
        with:
          registry: cr.lab.cip.uw.edu
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: build and push
        run: make push

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
